wandb_version: 1

model:
  desc: null
  value:
    model:
      _target_: aasist.AASIST.Model
      d_args:
        architecture: AASIST
        nb_samp: 64600
        first_conv: 128
        filts:
        - 70
        - - 1
          - 32
        - - 32
          - 32
        - - 32
          - 64
        - - 64
          - 64
        gat_dims:
        - 64
        - 32
        pool_ratios:
        - 0.5
        - 0.7
        - 0.5
        - 0.5
        temperatures:
        - 2.0
        - 2.0
        - 100.0
        - 100.0
train:
  desc: null
  value:
    num_epochs: 100
    update_interval: 3
    interval: 1
    gpu_index: 0
    optim:
      _target_: torch.optim.Adam
      lr: 0.0001
      betas:
      - 0.9
      - 0.999
      weight_decay: 0.0001
      eps: 1.0e-08
      amsgrad: false
    scheduler:
      _target_: torch.optim.lr_scheduler.CosineAnnealingLR
      T_max: ${..num_epochs}
      eta_min: 5.0e-06
test:
  desc: null
  value:
    test_only: false
    test_model: model/feat_model.pt
    scoring: null
    save_socre: score
    save_center: true
    dp: true
    test_one_hot: true
loss:
  desc: null
  value:
    name: samo
    fn:
      _target_: samo.loss.SAMO
      m_real: 0.7
      m_fake: 0
      alpha: 20
path_to_database:
  desc: null
  value: LA
output_folder:
  desc: null
  value: samo_output
overwrite:
  desc: null
  value: true
enc_dim:
  desc: null
  value: 160
batch_size:
  desc: null
  value: 23
target_only:
  desc: null
  value: true
initialize_centers:
  desc: null
  value: one_hot
verbose:
  desc: null
  value: false
seed:
  desc: null
  value: 10
continue_training:
  desc: null
  value: false
checkpoint:
  desc: null
  value: null
test_only:
  desc: null
  value: false
final_test:
  desc: null
  value: true
test_interval:
  desc: null
  value: 5
save_interval:
  desc: null
  value: 5
sampling_rate:
  desc: null
  value: 16000
dp:
  desc: null
  value: true
device:
  desc: null
  value: cpu
gpu:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719593239.0
    t:
      1:
      - 1
      - 11
      - 49
      - 50
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 50
      - 55
      - 105
      3:
      - 1
      - 2
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.16.4
      6: 4.35.0
      8:
      - 4
      - 5
      13: darwin-arm64
