defaults:
  - model: aasist
  - train: train
  - test: test
  - loss: samo
  - _self_

# Data folder
path_to_database: LA
output_folder: samo_output
overwrite: false

# Dataset prepare
enc_dim: 160
batch_size: 23
target_only: true # only target utterance

# Misc.
verbose: false
seed: 10
continue_training: false
checkpoint: null

final_test: true #run best model EER ont test set
test_interval: 5 # test on eval for every how many epoch
save_interval: 5 # save checkpoint for every how many epoch

sampling_rate: 16000
dp: true # nn.DataParallel
device: cuda
gpu: 0
